In [1]:
import numpy as np

## 1. Calculating Total Revenue

In [2]:
prices = np.array([19.99, 25.99, 14.99, 9.99, 29.99])
prices

array([19.99, 25.99, 14.99,  9.99, 29.99])

In [3]:
quantities = np.array([13, 8, 4, 21, 92])
quantities

array([13,  8,  4, 21, 92])

In [4]:
revenue_per_product = prices * quantities
revenue_per_product

array([ 259.87,  207.92,   59.96,  209.79, 2759.08])

In [5]:
total_revenue = np.sum(revenue_per_product)
total_revenue

np.float64(3496.62)

## 2. Analyzing Blog Post Stats

In [6]:
views = np.array([1000, 700, 300, 1400, 500])
views

array([1000,  700,  300, 1400,  500])

In [7]:
max_views = np.max(views)
max_views

np.int64(1400)

In [8]:
min_views = np.min(views)
min_views

np.int64(300)

In [9]:
avg_views = np.mean(views)
avg_views

np.float64(780.0)

In [10]:
avg_views = np.round(np.mean(views), 4)
avg_views

np.float64(780.0)

In [11]:
total_views = np.sum(views)
total_views

np.int64(3900)

## 3. Splitting Order Into Batches

In [12]:
order_ids = np.array([1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])
order_ids

array([1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])

In [13]:
batches = np.split(order_ids, 2)
batches

[array([1000, 1001, 1002, 1003, 1004]), array([1005, 1006, 1007, 1008, 1009])]

In [14]:
for batch in batches:
    print(batch)

[1000 1001 1002 1003 1004]
[1005 1006 1007 1008 1009]


In [15]:
for batch in batches:
    print("First element in the batch: ", batch[0])

First element in the batch:  1000
First element in the batch:  1005


In [16]:
for i, batch in enumerate(batches):
    print(f"Batch number {i}: ")
    print("First element in the batch: ", batch[0])
    print("Second element in the batch: ", batch[1])
    print('')

Batch number 0: 
First element in the batch:  1000
Second element in the batch:  1001

Batch number 1: 
First element in the batch:  1005
Second element in the batch:  1006



## 4. Categorizing Product Rating

In [17]:
ratings = np.array([4.8, 3.4, 4.3, 2.9, 3.9, 4.5, 2.3])
ratings

array([4.8, 3.4, 4.3, 2.9, 3.9, 4.5, 2.3])

In [18]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.8, 4.3, 4.5])

In [19]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.4, 2.9, 3.9, 2.3])

## 5. Calculate Total And Average Quantities Sold

In [20]:
# Each colum is a specific product (4)
# Each row is a specific order (2)
order_quantities = np.array([[5, 13, 7, 3], [6, 4, 9, 14]])
order_quantities

array([[ 5, 13,  7,  3],
       [ 6,  4,  9, 14]])

In [21]:
# Quantities of the sales per product
total_quantities_sold = np.sum(order_quantities, axis=0)
total_quantities_sold

array([11, 17, 16, 17])

In [22]:
# Quantities of the sales per order
total_quantities_sold = np.sum(order_quantities, axis=1)
total_quantities_sold

array([28, 33])

In [23]:
# Average quantities per product across all orders
avg_quantities_sold = np.mean(order_quantities, axis=0)
avg_quantities_sold

array([5.5, 8.5, 8. , 8.5])

## 6. Calculate Avg Product Rating & Max Rating Per Category

In [24]:
# Each row is one product
# Each product is rated in 4 category
product_rating = np.array([
    [4.5, 3.4, 4.1, 3.6],
    [4.2, 4.7, 3.8, 3.7],
    [3.2, 4.1, 4.3, 4.8]
])
product_rating

array([[4.5, 3.4, 4.1, 3.6],
       [4.2, 4.7, 3.8, 3.7],
       [3.2, 4.1, 4.3, 4.8]])

In [25]:
avg_product_rating_per_cat = np.mean(product_rating, axis=0)
avg_product_rating_per_cat

array([3.96666667, 4.06666667, 4.06666667, 4.03333333])

In [26]:
avg_product_rating_per_prod = np.mean(product_rating, axis=1)
avg_product_rating_per_prod

array([3.9, 4.1, 4.1])

In [27]:
max_product_rating = np.max(product_rating, axis=0)
max_product_rating

array([4.5, 4.7, 4.3, 4.8])

## 7. Generation of the sample stock data

In [28]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 June', 'Tue 2 June']
price_types = ['Open', 'Close', 'High', 'Low']

In [31]:
# shape = (3, 2, 4)
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [32]:
stock_prices.shape

(3, 2, 4)

In [34]:
for index_axis_0, company in enumerate(companies):
    print(f'Stock prices for {company}:')
    for index_axis_1, day in enumerate(days):
        print(f'Day is {day}')
        for index_axis_2, price_type in enumerate(price_types):
            print(f'Price type: {price_type}\n Price: {stock_prices[index_axis_0][index_axis_1][index_axis_2]}')
        print('')
    print('')

Stock prices for Google:
Day is Mon 1 June
Price type: Open
 Price: 0.417
Price type: Close
 Price: 0.72
Price type: High
 Price: 0.0
Price type: Low
 Price: 0.302

Day is Tue 2 June
Price type: Open
 Price: 0.147
Price type: Close
 Price: 0.092
Price type: High
 Price: 0.186
Price type: Low
 Price: 0.346


Stock prices for Microsoft:
Day is Mon 1 June
Price type: Open
 Price: 0.397
Price type: Close
 Price: 0.539
Price type: High
 Price: 0.419
Price type: Low
 Price: 0.685

Day is Tue 2 June
Price type: Open
 Price: 0.204
Price type: Close
 Price: 0.878
Price type: High
 Price: 0.027
Price type: Low
 Price: 0.67


Stock prices for Apple:
Day is Mon 1 June
Price type: Open
 Price: 0.417
Price type: Close
 Price: 0.559
Price type: High
 Price: 0.14
Price type: Low
 Price: 0.198

Day is Tue 2 June
Price type: Open
 Price: 0.801
Price type: Close
 Price: 0.968
Price type: High
 Price: 0.313
Price type: Low
 Price: 0.692


