In [1]:
import numpy as np

In [12]:
first = np.array([[1, 2, 3], [4, 5, 6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
first.ndim

2

In [16]:
second = np.array([[7, 8, 9], [10, 11, 12]])
second

array([[ 7,  8,  9],
       [10, 11, 12]])

In [17]:
second.shape

(2, 3)

In [19]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [20]:
first + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
first - 10

array([[-9, -8, -7],
       [-6, -5, -4]])

In [22]:
first * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [23]:
first / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [24]:
first

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
first[1, 2]

np.int64(6)

In [26]:
np.concatenate((first, second))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
np.concatenate((first, second), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [29]:
np.concatenate((np.array([1, 2, 3, 4]), np.array([5, 6, 7, 8])))

array([1, 2, 3, 4, 5, 6, 7, 8])