In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(16, 30)

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [5]:
np.arange(-30, 20, 5)

array([-30, -25, -20, -15, -10,  -5,   0,   5,  10,  15])

In [6]:
np.arange(start=-30, stop=20, step=5)

array([-30, -25, -20, -15, -10,  -5,   0,   5,  10,  15])

In [7]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
np.arange(30).reshape(3, 2, 5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [9]:
np.arange(30).reshape(3, 2, 5).reshape(6, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [10]:
np.random.random((10, )).reshape(2, 5)

array([[0.97864244, 0.04665251, 0.88626792, 0.86232077, 0.7591272 ],
       [0.1947274 , 0.44069219, 0.78792834, 0.80637295, 0.3776871 ]])

In [12]:
np.random.seed(10)
np.random.randint(50, 80, (2, 4, 3))

array([[[59, 79, 54],
        [65, 50, 67],
        [77, 78, 75],
        [79, 66, 79]],

       [[67, 76, 58],
        [59, 50, 60],
        [58, 72, 54],
        [69, 66, 54]]], dtype=int32)

In [13]:
np.random.seed(10)
np.random.randint(50, 80, (2, 4, 3)).flatten()

array([59, 79, 54, 65, 50, 67, 77, 78, 75, 79, 66, 79, 67, 76, 58, 59, 50,
       60, 58, 72, 54, 69, 66, 54], dtype=int32)

In [14]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])