In [12]:
import numpy as np

In [13]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((3, 4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
np.zeros((2, 4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [16]:
np.ones((3, 5), dtype=np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [19]:
np.random.seed(0)
np.random.random((3, 5))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [20]:
np.random.randint(5, size=(3, 5))

array([[1, 4, 3, 0, 3],
       [0, 2, 3, 0, 1],
       [3, 3, 3, 0, 1]], dtype=int32)

In [25]:
np.random.seed(0)
np.random.randint(5, 15, size=(3, 5))

array([[10,  5,  8,  8, 12],
       [14,  8, 10,  7,  9],
       [12, 11, 13, 13,  6]], dtype=int32)

In [27]:
np.random.seed(0)
np.random.uniform(size=(3, 5))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [29]:
np.random.seed(0)
np.random.uniform(15.0, 39.5, size=(3, 5))

array([[28.44593085, 32.52213948, 29.76770271, 28.34963798, 25.37954258],
       [30.82440577, 25.72088668, 36.84843852, 38.60973763, 24.39431721],
       [34.39726343, 27.95792553, 28.91709175, 37.67711764, 16.74038343]])

In [30]:
np.random.seed(10)
np.random.choice(np.array(['a', 'b', 'c']), size=(3, 5))

array([['b', 'b', 'a', 'a', 'b'],
       ['a', 'b', 'b', 'a', 'b'],
       ['b', 'c', 'a', 'b', 'a']], dtype='<U1')

In [34]:
np.random.seed(10)
np.random.choice(np.array(['a', 'b', 'c']), size=10)

array(['b', 'b', 'a', 'a', 'b', 'a', 'b', 'b', 'a', 'b'], dtype='<U1')